<x-article-page
    :title="$article->title"
    :perex="$article->perex"
    :content="$article->content"
    :embedUrl="$article->embed_url"
    :titleImage="$article->title_image"
    :tags="$article->tags->pluck('name')"
>
</x-article-page>
